(in-package :jack.tools.matrices)

(defun load-matrix (path)
  (let* ((input (unquote (cl-csv:read-csv (pathname path))))
	 (index (pop input)))
    (values (mgl-mat:make-mat (list (length input) (length index))
			      :ctype :double :initial-contents input)
	    index)))

(defun test ()
  (multiple-value-bind (herb-matrix herb-index)
      (load-matrix "/Users/asclepius/.roswell/local-projects/asclepius-core/data/processed/formula_herb.csv")
    (multiple-value-bind (manifest-matrix manifest-index)
	(load-matrix "/Users/asclepius/.roswell/local-projects/asclepius-core/data/processed/formula_manifest.csv")
      (values (mgl-mat:m* herb-matrix manifest-matrix :transpose-a? t)
	      (list herb-index manifest-index)))))
